name: weixin
on:
  workflow_dispatch:
  schedule: 
    # 代表国际标准时间21点30分，北京时间需要+8小时，代表北京时间上午5点30分点运行
    - cron: '50 23 * * *'
jobs:
#将工作流程中运行的所有作业组合在一起
  build:
  #定义名为 build 的作业。 子键将定义作业的属性 
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v2
    
      - name: weixin
        run: |
          java -jar WXPushForLoafOnTheJob.jar
